# Generated by Django 4.2.16 on 2024-09-22 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
