# Generated by Django 4.2.16 on 2024-09-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0005_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='password',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='trainer',
            name='type',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
    ]
