# Generated by Django 4.2.16 on 2024-09-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0006_trainer_password_trainer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
