# Generated by Django 4.2.16 on 2024-09-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0009_country_district_state_student_district_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='confirm_password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
