# Generated by Django 4.2.16 on 2024-09-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0010_alter_student_confirm_password_alter_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='confirm_password',
        ),
    ]
