# Generated by Django 4.2.16 on 2024-09-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0011_remove_student_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='managerapp.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managerapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerapp.cart')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerapp.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managerapp.student')),
            ],
        ),
    ]
