# Generated by Django 4.2.16 on 2024-09-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0014_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='skype_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='whatsapp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
