# Generated by Django 4.2.16 on 2024-09-22 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='TrainerRating',
        ),
    ]
