# Generated by Django 4.2.16 on 2024-09-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_remove_course_trainer_delete_trainerrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchasedCourse',
        ),
    ]
