# Generated by Django 4.2.16 on 2024-09-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0002_remove_video_course_delete_trainer_delete_video'),
        ('studentapp', '0004_delete_purchasedcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='purchased_courses',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='StudentProgress',
        ),
    ]
