# Generated by Django 4.2.16 on 2024-09-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
