# Generated by Django 4.2.16 on 2024-09-24 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managerapp', '0008_trainer_username'),
        ('trainerapp', '0002_remove_video_course_delete_trainer_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='course_videos/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='managerapp.course')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerapp.trainer')),
            ],
        ),
    ]
