# Generated by Django 4.2.16 on 2024-09-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0013_order'),
        ('trainerapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False)),
                ('watch_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerapp.student')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainerapp.video')),
            ],
        ),
    ]
